version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-bank
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22182:2182"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-bank
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    image: postgres
    volumes:
      - ./data2/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres/keycloak"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_IMPORT: /opt/keycloak/data/import/realm-config.json
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    ports:
      - "8084:8080"
  person-api:
    image: "glaptev8/person-api:v0.0"
    environment:
      SPRING_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/person"
      FLYWAY_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/person"
      SPRING_DATASOURCE_USERNAME: "postgres"
      KAFKA_HOST: "http://kafka:9093"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    pull_policy: always
    ports:
      - "8086:8080"
    depends_on:
      - postgres
  notification-api:
    image: "glaptev8/notification-api:v0.0"
    environment:
      SPRING_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/notifications"
      FLYWAY_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/notifications"
      SPRING_DATASOURCE_USERNAME: "postgres"
      KAFKA_HOST: "http://kafka:9093"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    ports:
      - "8088:8080"
    depends_on:
      - postgres
      - person-api
  individual:
    image: "glaptev8/individuals:v0.0"
    environment:
      PERSON_URL: "http://person-api:8080/api/v1/user"
      AUTH_SERVER_URL: "http://keycloak:8080"
      CERT: "http://keycloak:8080/realms/bank/protocol/openid-connect/certs"
      ISSUER_URI: "http://keycloak:8080/realms/bank"
    ports:
      - "8087:8080"
    depends_on:
      - postgres
      - keycloak
      - person-api
  user-api:
    image: "glaptev8/user-api:v0.0"
    environment:
      SPRING_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/user_api"
      FLYWAY_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/user_api"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    pull_policy: always
    ports:
      - "8089:8080"
  payments:
    image: "glaptev8/payments:v0.0"
    environment:
      SPRING_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/payments"
      FLYWAY_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/payments"
      SPRING_DATASOURCE_USERNAME: "postgres"
      PERSON_URL: "http://person-api:8080/api/v1/user"
      USER_URL: "http://user-api:8080/api/v1/wallets"
      PAYMENT_PROVIDER_URL: "http://payment-provider:8080/api/v1/payments"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    pull_policy: always
    ports:
      - "8090:8080"
  payment-provider:
    image: "glaptev8/payment-provider:v0.0"
    environment:
      SPRING_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/payment_provider"
      FLYWAY_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/payment_provider"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    ports:
      - "8092:8080"
    depends_on:
      - postgres
