keycloak:
  auth-server-url: ${AUTH_SERVER_URL}
  realm: bank
  scope: openid
  secret: wraaupXqE5JovEsvsTt284YsDvuyeDxf
  cert: ${CERT}
  client-id: admin

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
        registration:
          keycloak:
            client-id: admin