keycloak:
  auth-server-url: http://localhost:8084
  realm: bank
  scope: openid
  secret: wraaupXqE5JovEsvsTt284YsDvuyeDxf
  cert: http://localhost:8084/realms/bank/protocol/openid-connect/certs
  client-id: admin

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8084/realms/bank
        registration:
          keycloak:
            client-id: admin

server:
  port: 8087

integration:
  person-property:
    base-url: "http://localhost:8082/api/v1/user"
    save: "save"
    verify: "verify"